### PR TITLE
Tag 1.24.1 custom styling

### PR DESCRIPTION
**Pull request by ivermac**
closes https://github.com/onaio/zebra/issues/3683
closes https://github.com/onaio/enketo-express/issues/10

### CODE REVIEW

**Comment by ivermac** [comment]
This issue is related to https://github.com/onaio/zebra/issues/3683

**Comment by pld** [comment]
I like this, I think it could go into upstream enketo, you should open a PR with some explanation, you'll probably also need to modify the documentation to explain the new config key

**Comment by ivermac** [comment]
cool

**Comment by pld** [comment]
replaced w/https://github.com/onaio/enketo-express/pull/20

**Pull request closed without merging**
